ccflags-y += -Idrivers/media/platform/msm/camera_v2_j75
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j75/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j75/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
