ccflags-y += -Idrivers/media/platform/msm/camera_v2_on7n
ccflags-y += -Idrivers/media/platform/msm/camera_v2_on7n/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_on7n/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
