ccflags-y += -Idrivers/media/platform/msm/camera_v2_j3
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j3/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j3/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
