ccflags-y += -Idrivers/media/platform/msm/camera_v2_on7n
ccflags-y += -Idrivers/media/platform/msm/camera_v2_on7n/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_on7n/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
