ccflags-y += -Idrivers/media/platform/msm/camera_v2_j75
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j75/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_j75/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
